// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzMCnd51nyhoz_-V_fFBbz1FdrrCg5dxo',
    appId: '1:457031073270:web:c37a1e098d778488aedbd7',
    messagingSenderId: '457031073270',
    projectId: 'tienda-pet-movil',
    authDomain: 'tienda-pet-movil.firebaseapp.com',
    storageBucket: 'tienda-pet-movil.appspot.com',
    measurementId: 'G-JM04F9XFBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC4RnMjU2_NxqBMovfOxh_9OAjZdYoBPs',
    appId: '1:457031073270:android:a7aab66b42a61a1aaedbd7',
    messagingSenderId: '457031073270',
    projectId: 'tienda-pet-movil',
    storageBucket: 'tienda-pet-movil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIhKSkIZxDvpMiaxvrisobwg98cz1CUSg',
    appId: '1:457031073270:ios:f73b9a632b5900baaedbd7',
    messagingSenderId: '457031073270',
    projectId: 'tienda-pet-movil',
    storageBucket: 'tienda-pet-movil.appspot.com',
    iosClientId: '457031073270-oa0p1o6ssqkp375ghfa8bvr3gqkfeido.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiendaPetMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIhKSkIZxDvpMiaxvrisobwg98cz1CUSg',
    appId: '1:457031073270:ios:f73b9a632b5900baaedbd7',
    messagingSenderId: '457031073270',
    projectId: 'tienda-pet-movil',
    storageBucket: 'tienda-pet-movil.appspot.com',
    iosClientId: '457031073270-oa0p1o6ssqkp375ghfa8bvr3gqkfeido.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiendaPetMovil',
  );
}
